alter table EMPRESA_CONDICION_COMERCIAL add  CON_HES int;
update  EMPRESA_CONDICION_COMERCIAL  
set CON_HES = 0;
alter table EMPRESA_CONDICION_COMERCIAL add  CON_MIGO int;
update  EMPRESA_CONDICION_COMERCIAL  
set CON_MIGO = 0;
