  --alter table curriculo add PORCE_ASISTENCIA int null
  --alter table curriculo add PORCE_CALIFICACION int null

  --update [CURRICULO]
  --set PORCE_ASISTENCIA = 100, PORCE_CALIFICACION = 100


--create table dbmas.dbo.EMPRESAS_USUARIOS(
--ID_EMPRESAS_USUARIOS INT IDENTITY(1,1) NOT NULL,
--ID_EMPRESA INT NOT NULL, 
--NOMBRE VARCHAR(50) NULL,
--EMAIL VARCHAR(50) NULL,
--TELEFONO VARCHAR(50) NULL,
--CARGO VARCHAR(50) NULL, 
--CONTRASENA VARCHAR(50) NULL,
--ESTADO INT NULL,
--Rut_Empresa varchar(11) null
--)

--create table dbmas.dbo.EMPRESAS_OC(
--ID_EMPRESAS_OC INT IDENTITY(1,1) NOT NULL,
--ID_EMPRESA INT NOT NULL, 
--NRO_OC VARCHAR(50) NULL,
--MONTOOC INT NULL, 
--MONTOUTILIZADO INT NULL, 
--DESCRIPCION VARCHAR(50) NULL,
--NOMBREARCHIVO VARCHAR(200) NULL,
--RUTA_ARCHIVO VARCHAR(100) NULL,
--FECHACREACION DATETIME NULL
--)

--INSERT INTO EMPRESAS_USUARIOS (ID_EMPRESA, NOMBRE, EMAIL, TELEFONO, CARGO, CONTRASENA, ESTADO)
--SELECT ID_EMPRESA, NOMBRES AS NOMBRE, EMAIL, FONO_CONTACTO AS TELEFONO, 'contacto de coordinacion', PASSWORD_COORDINACION AS CONTRASEÑA, ESTADO  FROM EMPRESAS


--INSERT INTO EMPRESAS_USUARIOS (ID_EMPRESA, NOMBRE, EMAIL, TELEFONO, CARGO, CONTRASENA, ESTADO)
--SELECT ID_EMPRESA, NOMBRE_CONTA AS NOMBRE, EMAIL_CONTA, FONO_CONTABILIDAD AS TELEFONO, 'contacto de contabilidad', PASSWORD_CONTA AS CONTRASEÑA, ESTADO  FROM EMPRESAS

